Turn PYOP2_SPMD_STRICT back on
The recent change to caching hasn't fixed the occasional error:

OSError: dlopen(/Users/github-runner/.cache/pyop2/8c/578476a3cb4dfb9b270c466e10f804make_so.so, 0x0006): tried: '/Users/github-runner/.cache/pyop2/8c/578476a3cb4dfb9b270c466e10f804make_so.so' (file inode changed from 0xCE5D22 to 0xCE5D20 since Loader was built for '/Users/github-runner/.cache/pyop2/8c/578476a3cb4dfb9b270c466e10f804make_so.so'), '/System/Volumes/Preboot/Cryptexes/OS/Users/github-runner/.cache/pyop2/8c/578476a3cb4dfb9b270c466e10f804make_so.so' (no such file), '/Users/github-runner/.cache/pyop2/8c/578476a3cb4dfb9b270c466e10f804make_so.so' (file inode changed from 0xCE5D18 to 0xCE5D23 since Loader was built for '/Users/github-runner/.cache/pyop2/8c/578476a3cb4dfb9b270c466e10f804make_so.so')